### ISSUE TITLE
Email previews were confusing to setup

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/breeze#23]
**NOTE**
This is just feedback as I am messing around.

We have an abstract [`Carbon::EmailPreviews`](https://github.com/luckyframework/breeze/blob/0d6e7b3bcb315d25e36e694dd68bc6c11744b595/src/extensions/email_previews.cr#L2) with an abstract `previews` method that returns a hash. We currently [only allow one class to be passed in](https://github.com/luckyframework/breeze/blob/0d6e7b3bcb315d25e36e694dd68bc6c11744b595/src/extensions/carbon.cr#L9) and we provide one class-level  method that only "news" up the instance to access the hash.

I had a bit of confusion about using this class:
- No docs on how to set up the class (totally fine and expected)
- I had to cast my email to `Carbon::Email` to use it in the hash
```crystal
def previews
  {
    "User Confirmation" => UserConfirmationEmail.new(UserQuery.first).as(Carbon::Email)
  }
end
```
- The preview requires there to be a user in the database for it to work

Maybe we can switch to class-level methods to register email previews and make it a bit easier to work with with?

```crystal
class Email::Previews < Carbon::EmailPreviews
  register "User Confirmation" do
    UserConfirmationEmail.new(UserQuery.first)
  end
end
```

It's just an idea, but maybe it will make the API cleaner?

**Comment by jwoertink** [comment]
Ah. So it's sort of a Crystal related thing, but if you cast your hash as `of String => Carbon::Email`, then each email doesn't have to be cast separately. We do the same thing in the [AppServer](https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/src/app_server.cr.ecr#L21). We could probably make a generator that sets it up for you with some docs and examples. `lucky gen.email_preview`

I ado agree it's a little wonky though. I had a lot of issues trying to get this setup in another way. I kept running in to weird compiler issues. If you can figure out a better interface that's a bit more type-safe and user friendly, I'd be open to that.

**Comment by jwoertink** [comment]
The preview setup is a lot more simple now, and works similar to how our middleware stack works. I'm going to close this for now.
