### ISSUE TITLE
Need a "reset" button

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/breeze#7]
or do we? 🤔 

My "queries" page is getting LOADED with the login query. I have like 6 pages of `SELECT users.id, users.created_at, users.updated_at, users.email, users.encrypted_password FROM users ORDER BY users.id ASC LIMIT 1`... 

I'm thinking maybe there's a button to clear all those? Easy to reset all the data in case you want a quick refresh. The downside might be if you had some data that was tracking a specific bug, then you cleared it out and needed to get some info from it.... I guess that just falls on your though.

**Comment by matthewmcgarvey** [comment]
I was a little surprised to see that we are writing to the database. I would have expected that breeze would only keep things that happened during that app session and the data would be gone if recompiled/restarted

**Comment by matthewmcgarvey** [comment]
Before I forget, have you seen ScoutAPM's grouping of sql queries. It groups the same/similar queries together so that it isn't a huuuge list of sql calls. Maybe we could do that instead and have one listing for the login query and just say that it has been called 100 times or something like that

![CleanShot 2021-03-08 at 09 25 17](https://user-images.githubusercontent.com/17329408/110334085-5fbc8100-7ff0-11eb-8b62-781c5beb4e01.png)

**Comment by jwoertink** [comment]
I haven't seen that, but that's pretty nice! 

On the request page, we group all of the queries for that one request. It's just we have a separate page that lists out all of the queries. we might be able to group them, and do something similar. Maybe list how many times each call is done, and then somehow break out when each of those calls were made, and where in the app? 

But to your original surprise, I don't think we'd want to wipe things out on compile just because you might be doing tight small iterations testing something or tracking down a bug, and having all that data wiped out each time might make you lose your place. A button in the interface easily accessible would at least give you the ability to reset all of at the moment you need. I guess we could have a setting that auto does it for you, but have that turned off by default? 🤔

**Comment by jwoertink** [comment]
Oh, what about another task? `lucky breeze.data.clear` or something? The only downside I could think is if an extension added a model, then we wouldn't know which ones to wipe... But that could be another habitat config I guess. This makes it easier than a button with some ajax call or anything. Then it's just up to you. When you want to wipe it, just run the task.
